# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Code Analyzer

on:
  push:
    branches: [ "main" ]

jobs:
  analyze_code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

    - run: flutter pub get
      working-directory: app
    - name: Run Dart Analyzer
      run: dart analyze --fatal-warnings
    - name: Run Flutter Analyzer
      run: flutter analyze --fatal-warnings
      working-directory: app
